#!/usr/bin/env ruby
#Just a simple example command.
# @param <random> - Random Parameter 1
# @param - Random Parameter 2

def result(foo)
  # @param <foo>
  puts "It worked! 🎩✨ " + foo
end

result(ARGV.join(" "))
